package dataloader

const (
	EndpointConfig                 = "/interface.php?func=get_config"
	EndpointUnitConfig             = "/interface.php?func=get_unit_info"
	EndpointBuildingConfig         = "/interface.php?func=get_building_info"
	EndpointPlayer                 = "/map/player.txt.gz"
	EndpointPlayerNotGzipped       = "/map/player.txt"
	EndpointTribe                  = "/map/ally.txt.gz"
	EndpointTribeNotGzipped        = "/map/ally.txt"
	EndpointVillage                = "/map/village.txt.gz"
	EndpointVillageNotGzipped      = "/map/village.txt"
	EndpointKillAtt                = "/map/kill_att.txt.gz"
	EndpointKillAttNotGzipped      = "/map/kill_att.txt"
	EndpointKillDef                = "/map/kill_def.txt.gz"
	EndpointKillDefNotGzipped      = "/map/kill_def.txt"
	EndpointKillSup                = "/map/kill_sup.txt.gz"
	EndpointKillSupNotGzipped      = "/map/kill_sup.txt"
	EndpointKillAll                = "/map/kill_all.txt.gz"
	EndpointKillAllNotGzipped      = "/map/kill_all.txt"
	EndpointKillAttTribe           = "/map/kill_att_tribe.txt.gz"
	EndpointKillAttTribeNotGzipped = "/map/kill_att_tribe.txt"
	EndpointKillDefTribe           = "/map/kill_def_tribe.txt.gz"
	EndpointKillDefTribeNotGzipped = "/map/kill_def_tribe.txt"
	EndpointKillAllTribe           = "/map/kill_all_tribe.txt.gz"
	EndpointKillAllTribeNotGzipped = "/map/kill_all_tribe.txt"
	EndpointConquer                = "/map/conquer.txt.gz"
	EndpointConquerNotGzipped      = "/map/conquer.txt"
	EndpointGetConquer             = "/interface.php?func=get_conquer&since=%d"
)
